#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BugTracker.Resource", IsApplication=true)]

namespace BugTracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Priorities = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080019
			public const int addBug = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int addProject = 2131230744;
			
			// aapt resource value: 0x7f08000a
			public const int assigned2 = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int assigned2Title = 2131230729;
			
			// aapt resource value: 0x7f080013
			public const int bugsList = 2131230739;
			
			// aapt resource value: 0x7f08001a
			public const int editPreferences = 2131230746;
			
			// aapt resource value: 0x7f080001
			public const int expectedBehavior = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int expectedBehaviorTitle = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int @fixed = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int footerLinerLayout = 2131230731;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout1 = 2131230737;
			
			// aapt resource value: 0x7f080003
			public const int observedBehavior = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int observedBehaviorTitle = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int priority = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int priorityTitle = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int projectDescription = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int projectDescriptionTitle = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int projectName = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int projectNameTitle = 2131230733;
			
			// aapt resource value: 0x7f080017
			public const int project_description = 2131230743;
			
			// aapt resource value: 0x7f080015
			public const int project_icon = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int project_name = 2131230742;
			
			// aapt resource value: 0x7f080014
			public const int projectsList = 2131230740;
			
			// aapt resource value: 0x7f08000c
			public const int saveBug = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int saveProject = 2131230738;
			
			// aapt resource value: 0x7f080005
			public const int steps2Reproduce = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int steps2ReproduceTitle = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddBugLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddProjectLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BugsList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ProjectListRow = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int optionsMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int Assigned2 = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int DroidUtils = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ExpectedBehavior = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Fixed = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int ObservedBehavior = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int Priority = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int Save = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int Steps2reproduce = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int addBugTitle = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int addProjectTitle = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int editpreferences = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int projectDescription = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int projectName = 2131034124;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Preferences = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
